TRAIN_CONFIG:
  IMAGE_CONFIG:
    data_name: potsdam  # 数据集名字，解析各类编号以及上色现实
    image_size: 512
    image_mode: RGB  # Gray
    image_scale: [0.8, 1.5]
    image_path: /workspace/2/data/potsdam/
  MODEL_CONFIG:
    model_name: deeplab  # choice [deeplab, dinknet, lednet, ocrnet, hrnet, hrnet_up, hrnet_duc]
    backbone: resnet101  # choice [resnet50, resnet101, resnest50, resnest101, seresnet50, seresnet101, resnet50_cbam]
                         # resnet101_cbam, xception, resnest200, resnest269
    enhance: aspp  # choice [aspp, msfe]
    in_channels: 3
    num_classes: 6  # 最少是2
    output_stride: 16  # choice [8, 16]
    config_name: ''  # the config file for hrnet
  RUN_CONFIG:
    start_epoch: 1  # 起始轮次
    epoch: 50
    early_stop: 20  # 防止过拟合，早停轮次
    best_miou: 0
    batch_size: 12
    lr: 3e-4
    weight_decay: 4e-5
    use_gpu: True
    swa: False  # 是否使用SWA模型集成
    use_weight_balance: False  # 是否使用权重平衡，前提需要weight.txt文件  权重为1/(log(w_i)+1.02)
    device_ids: [0]
    num_workers: 4
    model_save_path: /workspace/2/data/potsdam/save_model
    weights_file: /workspace/2/data/potsdam/train/weight.txt
    pretrain: /workspace/2/data/potsdam/save_model/best_deeplab.pth
    loss_type: focal  # choice [ce, focal, dice, rmi]
TEST_CONFIG:
  test_path: /workspace/2/data/potsdam/valid/image/ # /workspace/2/data/vaihingen/patch/patch_image/
  label_path: /workspace/2/data/potsdam/valid/label/ # /workspace/2/data/vaihingen/patch/patch_label/
  save_result_path: /workspace/2/data/potsdam/valid/hrnet_org/ # /workspace/2/data/vaihingen/patch/hrnet_org/
  result_suffix: '.png'
  device_ids: [1]
  test_pretrain: /workspace/2/data/potsdam/save_model/best_hrnet_duc.pth # /workspace/2/data/vaihingen/save_model/best_hrnetv2_edge.pth
  test_image_size: 512
  test_stay_size: 300
  batch_size: 8
  multi_scale: [1]

